sudo: false
language: python
python:
    - '3.6'
install:
    - pip install -U flake8 pipenv setuptools wheel pip
    - pipenv install
before_script:
    - flake8 --ignore=W391 progressbar tests
script:
    - pipenv run python PlexMALSync.py
